image:
  repository: frostman/tweepub
  tag: "2017042401"
  pullPolicy: Always

twitter:
  appKey: EDITME
  appSecret: EDITME
  tokenKey: EDITME
  tokenSecret: EDITME

  #follow: twitter,kubernetesio
  #track: openstack,kubernetes,k8s,python,golang
  
  # SF & NYC:
  #locations: -122.75,36.8,-121.75,37.8,-74,40,-73,41
  
  # Boston:
  locations: -71.4415,41.9860,-70.4747,42.9041
  
  # Boston & SF & NYC
  # locations: -71.4415,41.9860,-70.4747,42.9041,-122.75,36.8,-121.75,37.8,-74,40,-73,41

  #languages: en

kafka:
  servers: kafka-kafka-1-0.kafka-kafka-1:9092
  topic: twitter-stream
