image:
  repository: frostman/tweeviz
  tag: "2017042604"
  pullPolicy: Always

hdfs:
  address: hdfs-namenode
  port: 8020
  path: /

minPopularity: 1
topListSize: 100

serviceType: NodePort
# nodePort: 33000
